# Looking back


## Media draft W4

  
*Now that you have submitted your draft for peer review, reflect on what you have  accomplished thus far. Use this worksheet ([download here](https://unsw-my.sharepoint.com/:f:/g/personal/z4513203_ad_unsw_edu_au/EnznzZ02XJJDppfyAfAcklYBy59ugHwuK_CZ8aUFYE82Qw?e=mOnIqI)) and write a few sentences (~100 words) responding to each of the following questions.* 
        
1.  On a scale of 0 to 10, how happy were you with the work you did getting your media draft submitted. Why did you give yourself that rating?  
<br> 
<br>
<br>
  
  
2. What could you have done differently, to make you feel better about how you did?  
<br> 
<br>
<br>  
  
  
3.	On a scale of 0 to 10, how adequately did you manage your time to complete the task? Why did you give yourself that rating?  
 <br> 
<br>
<br> 
  

4.	What tools did you use to help you get your draft in on time?
<br> 
<br>
<br>
  

5.	What obstacles were there and how did you deal with them? How might you deal with them going forward? 
<br> 
<br>
<br>  


## Peer review W5

6: Peer Feedback

*Giving (and receiving) feedback is an opportunity to learn and improve. Check out [this video](https://www.youtube.com/watch?v=qjg_wZtL9bc&feature=emb_logo) to see how feedback can help.* 

*Use this template ([download here](https://unsw-my.sharepoint.com/:f:/g/personal/z4513203_ad_unsw_edu_au/EnznzZ02XJJDppfyAfAcklYBy59ugHwuK_CZ8aUFYE82Qw?e=mOnIqI)) to reflect on what have you learned from and about the peer feedback process. Write a few sentences (~100words) to respond to each of the following questions.* 
  
  
1.	Before the peer review process, how did you feel about the idea of other students looking at your work? What were you worried about? 
<br> 
<br>
<br>  
  

2.	What surprised you about the process of reviewing and giving feedback to your peers?  
<br> 
<br>
<br>    
  

3.	What did you learn from the process of GIVING feedback to your peers? 
<br> 
<br>
<br>  


4.	What did you learn from the process of RECEIVING feedback from your peers?
<br> 
<br>
<br>  


5.	Some students report that the process of giving feedback to others is even more useful than receiving feedback on their own work. To what extent was this true for you?  
<br> 
<br>
<br>  

> This peer feedback worksheet was created by A/Prof Jenny Richmond, j.richmond@unsw.edu.au
  

## Rejoinder W7

*Revising your work in response to feedback is an opportunity to learn and improve. Check out [this video](https://www.youtube.com/watch?v=aXLroxyGNzM&feature=emb_logo) to see how other students approach working with feedback.* 

*A rejoinder is an opportunity to acknowledge or rebut feedback that you are given in an academic writing context. By critically thinking about whether the feedback you have received is justified and what action you could take to improve your work in response to it, you will be better able to revise and improve your media article for final submission.* 

*For each of your peer reviews, use this template ([download here](https://unsw-my.sharepoint.com/:f:/g/personal/z4513203_ad_unsw_edu_au/EnznzZ02XJJDppfyAfAcklYBy59ugHwuK_CZ8aUFYE82Qw?e=mOnIqI)) to comment on the quality of the feedback that you received and then reflect on whether each suggestion made by each reviewer was valid, and what you did to your revision to incorporate the feedback.*  
 
Reviewer ____ 
 
Comment on the quality of the feedback that you received from reviewer 1. To what extent was the feedback Specific, Actionable, Balanced, Thorough, and Constructive? 
<br> 
<br>
<br>  
 
 
Suggestion 1 
 
What did the reviewer suggest you do? Was this feedback valid? If not, why? If so, what did you do to incorporate their feedback in your revision?  
<br> 
<br>
<br> 
 

Suggestion 2 
 
What did the reviewer suggest you do? Was this feedback valid? If not, why? If so, what did you do to incorporate their feedback in your revision?  
<br> 
<br>
<br>  
 

Suggestion 3 
 
What did the reviewer suggest you do? Was this feedback valid? If not, why? If so, what did you do to incorporate their feedback in your revision?  
<br> 
<br>
<br>  
 


## Media final W8

*Now that you have submitted the final revision of your media article, reflect on how you went. Use this template ([download here](https://unsw-my.sharepoint.com/:f:/g/personal/z4513203_ad_unsw_edu_au/EnznzZ02XJJDppfyAfAcklYBy59ugHwuK_CZ8aUFYE82Qw?e=mOnIqI)) and write a few sentences (~100 words) responding to each of the following questions.* 
        
1.	On a scale of 0 to 10, how happy were you with the work you did getting your media draft submitted. Why did you give yourself that rating?  
<br>
<br>
<br>

2.	What could you have done differently, to make you feel better about how you did?  
<br>
<br>
<br>

3.	On a scale of 0 to 10, how adequately did you manage your time to complete the task? Why did you give yourself that rating?  
<br>
<br>
<br>


4.	What tools did you use to help you get your revision in on time?
<br>
<br>
<br>


5.	What obstacles were there and how did you deal with them? How might you deal with them going forward? 
<br>
<br>
<br>



